sudo: true
language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

before_install:
  - sudo apt-get install -y gnupg
  - openssl aes-256-cbc -K $encrypted_2b8c35c1fe04_key -iv $encrypted_2b8c35c1fe04_iv -in .travis/phar-private.pem.enc -out .travis/phar-private.pem -d
  - sudo curl -L -o /usr/local/bin/box https://github.com/humbug/box/releases/download/3.1.1/box.phar
  - sudo chmod 755 /usr/local/bin/box

install: composer install

script: vendor/bin/phpunit

before_deploy: build/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: gh-pages
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == "v2" || -n $TRAVIS_TAG
    php: '7.1'
