sudo: false
language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - EXECUTE_DEPLOYMENT=true
    - php: 7.2

before_install:
  - openssl aes-256-cbc -K $encrypted_2b8c35c1fe04_key -iv $encrypted_2b8c35c1fe04_iv -in .travis/phar-private.pem.enc -out .travis/phar-private.pem -d

script: build/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: gh-pages
  on:
    branch: v2
