sudo: true
language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

install: composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit

after_success:
  - travis_retry vendor/bin/php-coveralls

before_deploy:
  - sudo apt-get install -y gnupg
  - sudo curl -L -o /usr/local/bin/box https://github.com/humbug/box/releases/download/3.1.1/box.phar
  - sudo chmod 755 /usr/local/bin/box
  - openssl aes-256-cbc -K $encrypted_2b8c35c1fe04_key -iv $encrypted_2b8c35c1fe04_iv -in .travis/phar-private.pem.enc -out .travis/phar-private.pem -d
  - build/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: gh-pages
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
    php: '7.2'
